import { describe, expect, it } from 'vitest';
import { apyFromApr, cdBalanceFromApy, cdFinalBalance, cdFromApr } from '../src/lib/cd';

/**
 * Expected values: computed independently (Python Decimal/float, 2026-08-02)
 * from the standard compound-interest formula A = P(1+r/n)^(nt) as published
 * by investor.gov and finance textbooks — NOT generated by the implementation
 * under test. The $1,000 @ 6%/monthly/10y = $1,819.40 case is a widely
 * published textbook example of this formula.
 */
describe('cdFinalBalance', () => {
	it('matches the textbook example: $1,000 at 6% compounded monthly for 10 years', () => {
		expect(cdFinalBalance(1000, 0.06, 12, 10)).toBeCloseTo(1819.397, 2);
	});

	it('$10,000 at 5% compounded quarterly for 5 years', () => {
		expect(cdFinalBalance(10000, 0.05, 4, 5)).toBeCloseTo(12820.372, 2);
	});

	it('zero rate returns the principal unchanged', () => {
		expect(cdFinalBalance(5000, 0, 12, 3)).toBe(5000);
	});

	it('zero term returns the principal unchanged', () => {
		expect(cdFinalBalance(5000, 0.05, 12, 0)).toBe(5000);
	});

	it('handles fractional years (9-month CD)', () => {
		// 2500 * (1 + 0.04/12)^(12 * 0.75) — independently: 2500 * (1.0033333)^9
		expect(cdFinalBalance(2500, 0.04, 12, 0.75)).toBeCloseTo(2576.008, 2);
	});
});

describe('apyFromApr (Reg DD Appendix A: (1+r/n)^n - 1)', () => {
	it('5% compounded monthly -> 5.116% APY', () => {
		expect(apyFromApr(0.05, 12)).toBeCloseTo(0.0511619, 6);
	});

	it('4.75% compounded daily (365) -> 4.864% APY', () => {
		expect(apyFromApr(0.0475, 365)).toBeCloseTo(0.0486430, 6);
	});

	it('annual compounding: APY equals APR', () => {
		expect(apyFromApr(0.05, 1)).toBeCloseTo(0.05, 12);
	});
});

describe('cdBalanceFromApy', () => {
	it('$5,000 at 4.5% APY held 18 months', () => {
		expect(cdBalanceFromApy(5000, 0.045, 1.5)).toBeCloseTo(5341.27, 2);
	});

	it('one year at APY is exactly principal * (1 + APY)', () => {
		expect(cdBalanceFromApy(10000, 0.05, 1)).toBeCloseTo(10500, 8);
	});
});

describe('cdFromApr', () => {
	it('reports interest earned as balance minus principal', () => {
		const r = cdFromApr(1000, 0.06, 12, 10);
		expect(r.finalBalance).toBeCloseTo(1819.397, 2);
		expect(r.interestEarned).toBeCloseTo(819.397, 2);
		expect(r.apy).toBeCloseTo(0.0616778, 5); // (1+0.06/12)^12 - 1, independent calc
	});
});
