import { describe, expect, it } from 'vitest';
import { calculateMortgage, monthlyPrincipalInterest, remainingBalance } from '../src/lib/mortgage';

/**
 * Expected values: computed independently (Python float, 2026-08-05) from the
 * standard amortization formula M = P[r(1+r)^n]/[(1+r)^n-1] — NOT generated by
 * the implementation under test. $200,000 at 6% for 30 years -> $1,199.10/mo
 * is a widely published textbook/CFPB-adjacent example of this formula.
 */
describe('monthlyPrincipalInterest', () => {
	it('matches the widely published example: $200,000 at 6% for 30 years', () => {
		expect(monthlyPrincipalInterest(200000, 6.0, 30)).toBeCloseTo(1199.1011, 3);
	});

	it('$300,000 at 6.5% for 30 years', () => {
		expect(monthlyPrincipalInterest(300000, 6.5, 30)).toBeCloseTo(1896.2041, 3);
	});

	it('$400,000 at 5% for 15 years', () => {
		expect(monthlyPrincipalInterest(400000, 5.0, 15)).toBeCloseTo(3163.1745, 3);
	});

	it('$350,000 at 7.25% for 30 years', () => {
		expect(monthlyPrincipalInterest(350000, 7.25, 30)).toBeCloseTo(2387.6170, 3);
	});

	it('zero rate splits principal evenly across the term', () => {
		expect(monthlyPrincipalInterest(250000, 0, 30)).toBeCloseTo(694.4444, 3);
	});
});

describe('remainingBalance', () => {
	it('$300,000 at 6.5% for 30 years, after 5 years (60 payments)', () => {
		expect(remainingBalance(300000, 6.5, 30, 60)).toBeCloseTo(280832.93, 1);
	});

	it('$300,000 at 6.5% for 30 years, after 15 years (180 payments)', () => {
		expect(remainingBalance(300000, 6.5, 30, 180)).toBeCloseTo(217677.42, 1);
	});

	it('$200,000 at 6% for 30 years, after 1 year (12 payments)', () => {
		expect(remainingBalance(200000, 6.0, 30, 12)).toBeCloseTo(197543.98, 1);
	});

	it('at n = full term the balance is (approximately) zero', () => {
		expect(remainingBalance(200000, 6.0, 30, 360)).toBeCloseTo(0, 4);
	});

	it('zero rate: balance decreases linearly by the level payment', () => {
		expect(remainingBalance(250000, 0, 30, 120)).toBeCloseTo(166666.67, 1);
	});
});

describe('calculateMortgage', () => {
	it('derives loan amount from home price and down payment percentage', () => {
		const r = calculateMortgage({ homePrice: 400000, downPaymentPct: 20, annualRatePct: 6.5, termYears: 30 });
		expect(r.downPaymentAmount).toBeCloseTo(80000, 2);
		expect(r.loanAmount).toBeCloseTo(320000, 2);
	});

	it('$320,000 loan at 6.5% for 30 years: P&I, total interest, total paid', () => {
		const r = calculateMortgage({ homePrice: 400000, downPaymentPct: 20, annualRatePct: 6.5, termYears: 30 });
		expect(r.monthlyPI).toBeCloseTo(2022.6177, 3);
		expect(r.totalOfPayments).toBeCloseTo(r.monthlyPI * 360, 2);
		expect(r.totalInterest).toBeCloseTo(r.totalOfPayments - r.loanAmount, 2);
	});

	it('folds taxes, insurance, PMI and HOA into monthly escrow and total payment', () => {
		const r = calculateMortgage({
			homePrice: 400000,
			downPaymentPct: 20,
			annualRatePct: 6.5,
			termYears: 30,
			annualTax: 4800,
			annualInsurance: 1200,
			annualPmi: 0,
			monthlyHoa: 50,
		});
		expect(r.monthlyEscrow).toBeCloseTo(4800 / 12 + 1200 / 12 + 50, 4);
		expect(r.totalMonthlyPayment).toBeCloseTo(r.monthlyPI + r.monthlyEscrow, 4);
	});

	it('defaults optional escrow inputs to zero', () => {
		const r = calculateMortgage({ homePrice: 250000, downPaymentPct: 10, annualRatePct: 5.5, termYears: 15 });
		expect(r.monthlyEscrow).toBe(0);
		expect(r.totalMonthlyPayment).toBeCloseTo(r.monthlyPI, 6);
	});

	it('balanceByYear has one entry per year of the term, decreasing to ~0', () => {
		const r = calculateMortgage({ homePrice: 250000, downPaymentPct: 20, annualRatePct: 6.0, termYears: 15 });
		expect(r.balanceByYear).toHaveLength(15);
		expect(r.balanceByYear[0]!.year).toBe(1);
		expect(r.balanceByYear[14]!.year).toBe(15);
		expect(r.balanceByYear[14]!.balance).toBeCloseTo(0, 2);
		// Monotonically decreasing.
		for (let i = 1; i < r.balanceByYear.length; i++) {
			expect(r.balanceByYear[i]!.balance).toBeLessThan(r.balanceByYear[i - 1]!.balance);
		}
	});
});
