import { describe, expect, it } from 'vitest';
import { afterTaxCostOfDebt, calculateWacc, capmCostOfEquity, waccWeights } from '../src/lib/wacc';

/**
 * Expected values: computed independently (Python, 2026-08-23) from the
 * standard formulas WACC = (E/V)Re + (D/V)Rd(1-Tc) and CAPM Re = Rf + β(Rm-Rf)
 * as documented in Damodaran's (NYU Stern) valuation notes — NOT generated by
 * the implementation under test.
 */
describe('capmCostOfEquity', () => {
	it('Rf=4%, β=1.2, Rm=9% -> Re=10%', () => {
		// 0.04 + 1.2*(0.09-0.04) = 0.04 + 0.06 = 0.10
		expect(capmCostOfEquity(0.04, 1.2, 0.09)).toBeCloseTo(0.1, 10);
	});

	it('beta of 1 makes cost of equity equal the market return', () => {
		expect(capmCostOfEquity(0.03, 1, 0.08)).toBeCloseTo(0.08, 10);
	});

	it('negative beta: Rf=3%, β=-0.2, Rm=8% -> Re=2%', () => {
		// 0.03 + (-0.2)*(0.08-0.03) = 0.03 - 0.01 = 0.02
		expect(capmCostOfEquity(0.03, -0.2, 0.08)).toBeCloseTo(0.02, 10);
	});
});

describe('afterTaxCostOfDebt', () => {
	it('6% pretax at 21% tax rate -> 4.74% after-tax', () => {
		expect(afterTaxCostOfDebt(0.06, 0.21)).toBeCloseTo(0.0474, 10);
	});

	it('zero tax rate leaves the pretax rate unchanged', () => {
		expect(afterTaxCostOfDebt(0.08, 0)).toBeCloseTo(0.08, 10);
	});
});

describe('waccWeights', () => {
	it('$600M equity / $400M debt -> 60/40 split', () => {
		const w = waccWeights(600_000_000, 400_000_000);
		expect(w.weightEquity).toBeCloseTo(0.6, 10);
		expect(w.weightDebt).toBeCloseTo(0.4, 10);
	});

	it('all-equity company: weightDebt is 0', () => {
		const w = waccWeights(250_000, 0);
		expect(w.weightEquity).toBe(1);
		expect(w.weightDebt).toBe(0);
	});
});

describe('calculateWacc', () => {
	it('$600M equity @ Re=10%, $400M debt @ Rd=6% pretax, 21% tax -> WACC=7.896%', () => {
		const r = calculateWacc({
			equity: 600_000_000,
			debt: 400_000_000,
			costOfEquity: 0.1,
			costOfDebt: 0.06,
			taxRate: 0.21,
		});
		expect(r.weightEquity).toBeCloseTo(0.6, 10);
		expect(r.weightDebt).toBeCloseTo(0.4, 10);
		expect(r.afterTaxCostOfDebt).toBeCloseTo(0.0474, 10);
		expect(r.wacc).toBeCloseTo(0.07896, 8);
	});

	it('all-equity company: WACC equals cost of equity', () => {
		const r = calculateWacc({ equity: 250_000, debt: 0, costOfEquity: 0.115, costOfDebt: 0.07, taxRate: 0.21 });
		expect(r.wacc).toBeCloseTo(0.115, 10);
	});

	it('$3M equity @ 14%, $2M debt @ 8% pretax, 25% tax -> WACC=10.8%', () => {
		const r = calculateWacc({ equity: 3_000_000, debt: 2_000_000, costOfEquity: 0.14, costOfDebt: 0.08, taxRate: 0.25 });
		expect(r.afterTaxCostOfDebt).toBeCloseTo(0.06, 10);
		expect(r.wacc).toBeCloseTo(0.108, 10);
	});

	it('zero tax rate: same capital structure -> WACC=11.6%', () => {
		const r = calculateWacc({ equity: 3_000_000, debt: 2_000_000, costOfEquity: 0.14, costOfDebt: 0.08, taxRate: 0 });
		expect(r.afterTaxCostOfDebt).toBeCloseTo(0.08, 10);
		expect(r.wacc).toBeCloseTo(0.116, 10);
	});

	it('zero debt and zero equity input does not throw (caller validates before calling)', () => {
		// Documents the 0/0 edge case rather than guarding it silently — the UI
		// layer is responsible for requiring at least one of equity/debt > 0.
		const r = calculateWacc({ equity: 0, debt: 0, costOfEquity: 0.1, costOfDebt: 0.05, taxRate: 0.21 });
		expect(Number.isNaN(r.wacc)).toBe(true);
	});
});
