import { describe, expect, it } from 'vitest';
import { FONT_PRESETS, pagesFromWords, wordsFromPages, wordsPerPage } from '../src/lib/wordsToPages';

/**
 * Expected values: computed independently (Python, 2026-08-24) from the
 * formulas wordsPerPage = singleSpacedBaseline / spacingMultiplier and
 * pages = words / wordsPerPage — NOT generated by the implementation under
 * test. The 500 (single-spaced) / 250 (double-spaced) Times New Roman 12pt
 * baseline is the standard manuscript-format rule of thumb (William Shunn,
 * "Proper Manuscript Format"); Arial 470 and Calibri 575 are the midpoints
 * of the ranges reported across independent font/spacing word-count guides.
 */
describe('wordsPerPage', () => {
	it('Times New Roman 12pt, single-spaced -> 500 words/page', () => {
		expect(wordsPerPage(500, 1)).toBe(500);
	});

	it('Times New Roman 12pt, double-spaced -> 250 words/page', () => {
		expect(wordsPerPage(500, 2)).toBe(250);
	});

	it('Times New Roman 12pt, 1.15 lines -> ~434.78 words/page', () => {
		expect(wordsPerPage(500, 1.15)).toBeCloseTo(434.7826086956522, 8);
	});

	it('Times New Roman 12pt, 1.5 lines -> ~333.33 words/page', () => {
		expect(wordsPerPage(500, 1.5)).toBeCloseTo(333.3333333333333, 8);
	});

	it('Arial 12pt, double-spaced -> 235 words/page', () => {
		expect(wordsPerPage(470, 2)).toBe(235);
	});

	it('Calibri 11pt, double-spaced -> 287.5 words/page', () => {
		expect(wordsPerPage(575, 2)).toBe(287.5);
	});
});

describe('pagesFromWords', () => {
	it('1000 words double-spaced (250/page) -> 4 pages', () => {
		expect(pagesFromWords(1000, 250)).toBe(4);
	});

	it('1000 words single-spaced (500/page) -> 2 pages', () => {
		expect(pagesFromWords(1000, 500)).toBe(2);
	});

	it('500 words double-spaced -> 2 pages', () => {
		expect(pagesFromWords(500, 250)).toBe(2);
	});

	it('2000 words double-spaced -> 8 pages', () => {
		expect(pagesFromWords(2000, 250)).toBe(8);
	});

	it('5000 words double-spaced -> 20 pages', () => {
		expect(pagesFromWords(5000, 250)).toBe(20);
	});

	it('1500 words at 1.5-line spacing (333.33/page) -> 4.5 pages', () => {
		expect(pagesFromWords(1500, wordsPerPage(500, 1.5))).toBeCloseTo(4.5, 8);
	});

	it('0 words -> 0 pages', () => {
		expect(pagesFromWords(0, 250)).toBe(0);
	});
});

describe('wordsFromPages', () => {
	it('5 pages double-spaced (250/page) -> 1250 words', () => {
		expect(wordsFromPages(5, 250)).toBe(1250);
	});

	it('2 pages single-spaced (500/page) -> 1000 words', () => {
		expect(wordsFromPages(2, 500)).toBe(1000);
	});

	it('0 pages -> 0 words', () => {
		expect(wordsFromPages(0, 250)).toBe(0);
	});
});

describe('FONT_PRESETS', () => {
	it('has exactly the three documented presets in the documented order', () => {
		expect(FONT_PRESETS.map((f) => f.id)).toEqual(['times-12', 'arial-12', 'calibri-11']);
	});

	it('Times New Roman single-spaced baseline is exactly double the standard double-spaced figure', () => {
		const tnr = FONT_PRESETS.find((f) => f.id === 'times-12')!;
		expect(tnr.singleSpacedWordsPerPage).toBe(500);
		expect(tnr.singleSpacedWordsPerPage / 2).toBe(250);
	});
});
